### ISSUE TITLE
Conflict warning logged in all new sessions when adding an abbreviation in zshrc

### ISSUE THREAD

**Issue by martino2002** [olets/zsh-abbr#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Update the issue title

- [X] I have updated the title

### Expected Behavior

I have only one abbreviation, since I discovered this software just yesterday, I added these two lines in my .zshrc
source /home/linuxbrew/.linuxbrew/share/zsh-abbr/zsh-abbr.zsh, as indicated in the installation guide, and
abbr vid="vim ~/.local/share/applications/"

It works, but I would expect it to simply work without complaining, since I don't have anything else that could conflict with the abbreviation.

### Actual Behavior

And yet, it complains, as you might had guessed.
The error message is:
**Did not add the regular user abbreviation `vid`. It already has an expansion**
(and yet it was added, because it works)

What could be the problem?

### Steps To Reproduce

Added this abbreviation to .zshrc 
abbr vid="vim ~/.local/share/applications/"

### Environment

```shell
zsh-abbr version 5.1.0
zsh 5.9 (x86_64-pc-linux-gnu)
OSTYPE linux-gnu
```

### Installation method

Homebrew

### Installation method details

Added this to bottom of .zshrc as indicated in installation guide:
source /home/linuxbrew/.linuxbrew/share/zsh-abbr/zsh-abbr.zsh

**Comment by olets** [comment]
The fix is to remove

```shell
abbr vid="vim ~/.local/share/applications/"
```

from `.zshrc`. That will clear the error, and won't remove the abbreviation.

Everything in `.zshrc` is run every time you open a new terminal. So you're rerunning your `abbr` command every time you open a new terminal.

Typical use is to run `abbr` commands in a terminal (not in a configuration file).

**Comment by olets** [comment]
The fix is to remove

```shell
abbr vid="vim ~/.local/share/applications/"
```

from `.zshrc`. That will clear the error, and won't remove the abbreviation.

Everything in `.zshrc` is run every time you open a new terminal. So you're rerunning your `abbr` command every time you open a new terminal.

Typical use is to run `abbr` commands in a terminal (not in a configuration file).

Let me know if that doesn't resolve it for you. Hope abbr turns out to be useful!
